### ISSUE TITLE
wekanetperf crashing 

### ISSUE THREAD

**Issue by symon-swann** [weka/tools#36]
When running wekanetperf at MAAS the iperf sessions seem to run but then wekanetperf crashes before printing the results.

All servers are running RHEL 8.3 and iperf 2.1.6

> [root@Persephone install]# ./wekanetperf 172.27.90.101 172.27.90.102
> Opening ssh sessions to all servers
> 
> checking connectivity to 172.27.90.101
> connectivity successful, copying credentials to other servers
> opening ssh sessions to all servers
> Interface speed is 200.0 Gbits/s
> iperf servers started
> Running...
> Running...
> process complete
> Traceback (most recent call last):
>   File "wekanetperf.py", line 77, in <module>
>   File "iperf.py", line 106, in run_iperf
> ValueError: invalid literal for int() with base 10: 'connect'
> [110012] Failed to execute script 'wekanetperf' due to unhandled exception!
> 
> [root@Persephone install]# pdsh iperf --version
> apollo1: iperf version 2.1.6 (10 December 2021) pthreads
> pdsh@Persephone: apollo1: ssh exited with exit code 1
> apollo3: iperf version 2.1.6 (10 December 2021) pthreads
> apollo2: iperf version 2.1.6 (10 December 2021) pthreads
> pdsh@Persephone: apollo3: ssh exited with exit code 1
> pdsh@Persephone: apollo2: ssh exited with exit code 1
> apollo5: iperf version 2.1.6 (10 December 2021) pthreads
> pdsh@Persephone: apollo5: ssh exited with exit code 1
> apollo6: iperf version 2.1.6 (10 December 2021) pthreads
> pdsh@Persephone: apollo6: ssh exited with exit code 1
> apollo4: iperf version 2.1.6 (10 December 2021) pthreads
> pdsh@Persephone: apollo4: ssh exited with exit code 1
> [root@Persephone install]#

**Comment by vince-weka** [comment]
fixed in latest rev (I hope ;) )
