### ISSUE TITLE
weka_upgrade_checker.sh should be able to be run with sudo as long as the non-privileged account has ssh access to the remote host

### ISSUE THREAD

**Issue by sethmalone-weka** [weka/tools#66]
weka_upgrade_checker.sh requires passwordless SSH for root between backends.

Please enable running with sudo as long as the non-privileged user has passwordless SSH enabled between backends.

Use case: DRW - they don't let their storage team have root access on their backends.

**Comment by shazad-weka** [comment]
There are multiple 'weka' commands that require root privileges.

**Comment by sethmalone-weka** [comment]
Yes - the request is to accommodate this by using "sudo" for those commands.

**Comment by shazad-weka** [comment]
fix is implemented and will be included in the next release.

**Comment by shazad-weka** [comment]
updated script
