### ISSUE TITLE
weka_upgrade_checker.sh "Authentication Failed" error after "s3 container status running, is enabled and Minio is ready"

### ISSUE THREAD

**Issue by sethmalone-weka** [weka/tools#82]
"Authentication Failed" error after "s3 container status running, is enabled and Minio is ready" output

Note: this is in the context of a customer who does not run weka_upgrade_checker.sh as root (sudo is used)

> [1;32mHost <customer servername> s3 container status running, is enabled and Minio is ready.[0m
> error: Authentication Failed: 
> Please run this command to login to your cluster:
>
>     weka user login
> 
> If you pass your credentials using environment variables, please make sure
> to pass them in the WEKA_USERNAME/WEKA_PASSWORD environment variables.
> You may also need to pass WEKA_ORG to specify your organization ID or name.

**Comment by shazad-weka** [comment]
Issue is addressed in version 1.0.57, please wait until changes are merged into master or use commit e59d5a8 or use the following link `https://github.com/weka/tools/blob/e59d5a8c75d2d427c4e85ff2b86f156bc2c6ed78/postinstall/weka_upgrade_checker.sh`
